export const CalendarDetails = [
  {
    id: 1,
    name: "Advanced MS Excel",
    days: "2",
    dates: "15-16 Oct",
    investments: "6000",
    location: "Online",
    details: "View",
  },
  {
    id: 2,
    name: "PMP",
    days: "4",
    dates: "21-22 Oct",
    investments: "15000",
    location: "Online",
    details: "View",
  },
  {
    id: 3,
    name: "ITIL V3 2011 Foundation Training & Certification",
    days: "2",
    dates: "5-6 Nov",
    investments: "18000",
    location: "Online",
    details: "View",
  },
  {
    id: 4,
    name: "ISO 9001:2015 QMS Awareness cum Transition	",
    days: "1",
    dates: "8 Nov",
    investments: "5500",
    location: "Online",
    details: "View",
  },
  {
    id: 5,
    name: "HR Analytics",
    days: "2",
    dates: "11-12 Nov",
    investments: "9000",
    location: "Online",
    details: "View",
  },
  {
    id: 6,
    name: "Lean Six Sigma Yellow Belt (LSSYB) Certification	",
    days: "2",
    dates: "19-20 Nov",
    investments: "10000",
    location: "Online",
    details: "View",
  },
  {
    id: 7,
    name: "Value Stream Mapping (VSM)	",
    days: "1",
    dates: "13 Nov",
    investments: "5500",
    location: "Online",
    details: "View",
  },
  {
    id: 8,
    name: "Warehouse Management System",
    days: "1",
    dates: "26 Nov",
    investments: "5500",
    location: "Online",
    details: "View",
  },
  {
    id: 9,
    name: "Finance for Non-Finance	",
    days: "2",
    dates: "3-4 Dec",
    investments: "9000",
    location: "Online",
    details: "View",
  },
];
