export const technology = [
  { id: 1, technology: "React.js" },
  { id: 2, technology: "Java" },
  { id: 3, technology: "Node.js" },
  { id: 4, technology: "Python" },
  { id: 5, technology: "Agile" },
  { id: 6, technology: "PHP" },
  { id: 7, technology: "C" },
  { id: 8, technology: "Machine Learning" },
  { id: 9, technology: "Spring Boot" },
  { id: 10, technology: "RR" },
  { id: 11, technology: "Ruby" },
  { id: 12, technology: "Perl Scripting" },
  { id: 13, technology: "AJAX" },
  { id: 14, technology: "JavaScript" },
  { id: 15, technology: "TypeScript" },
  { id: 16, technology: "Web Designing" },
  { id: 17, technology: "Deep Learning" },
  { id: 18, technology: "Kubernetes" },
  { id: 19, technology: "DOCKER" },
  { id: 20, technology: "AWS" },
  { id: 21, technology: "Git & Github" },
  { id: 22, technology: "JIRA" },
  { id: 23, technology: "Jenkins" },
  { id: 24, technology: "Oracle" },
  { id: 25, technology: "MySQL" },
  { id: 26, technology: "SQL" },
  { id: 27, technology: "MongoDB" },
  { id: 28, technology: "MS Office" },
  { id: 29, technology: "MS Excel" },
  { id: 30, technology: "AZURE" },
  { id: 31, technology: "Cassandra" },
  { id: 32, technology: "MS Access" },
  { id: 33, technology: "PowerBI" },
  { id: 34, technology: "Hybris" },
  { id: 35, technology: "Postgre" },
  { id: 36, technology: "DB2" },
  { id: 37, technology: "Team Building" },
  { id: 38, technology: "Supervising" },
  { id: 39, technology: "Cyber Security" },
  { id: 40, technology: "Selling" },
  { id: 41, technology: "Interviewing" },
  { id: 42, technology: "Blockchain" },
  { id: 43, technology: "Artificial Intelligence" },
  { id: 44, technology: "Robotics" },
  { id: 45, technology: "IOT" },
  { id: 46, technology: "Lean Six Sigma" },
  { id: 47, technology: "PMP" },
  { id: 48, technology: "Kaizan" },
  { id: 49, technology: "AR/VR" },
];
