export const programCategory = [
  {
    id: 1,
    category: "Application Development",
    value: "applicationdevelopment",
  },
  {
    id: 2,
    category: "Cloud Technologies",
    value: "cloudtechnologies",
  },
  {
    id: 3,
    category: "DevOps",
    value: "devops",
  },
  {
    id: 4,
    category: "Cloud Infrastructure Services",
    value: "cloudservices",
  },
  {
    id: 5,
    category: "Niche / Other Trainings",
    value: "nichetrainings",
  },
  {
    id: 6,
    category: "Database Management",
    value: "databasemanagement",
  },
  {
    id: 7,
    category: "Soft/Behavioral Skills",
    value: "softskills",
  },
  {
    id: 8,
    category: "Emerging Technologies",
    value: "emergingtechnologies",
  },
  {
    id: 9,
    category: "Quality Management",
    value: "qualitymanagement",
  },
  {
    id: 10,
    category: "Project Management",
    value: "projectmanagement",
  },
];

// ------------------------------------------------------
// ------------------------------------------------------
// ------------------------------------------------------
// ------------------------------------------------------

export const applicationdevelopment = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Application Server", value: "applicationserver" },
  { id: 2, program: "ESB", value: "esb" },
  { id: 3, program: "OS", value: "os" },
  { id: 4, program: "Framework", value: "framework" },
  { id: 5, program: "Process", value: "process" },
  {
    id: 6,
    program: "Artificial Intelligence",
    value: "artificialintelligence",
  },
  { id: 7, program: "AS 400", value: "as400" },
  { id: 8, program: "Full Stack", value: "fullstack" },
  { id: 9, program: "Programming Languages", value: "programminglanguages" },
  { id: 10, program: "Machine Learning", value: "machinelearning" },
  { id: 11, program: "IaC/DevOps", value: "iacdevops" },
  { id: 12, program: "IOT", value: "iot" },
  { id: 13, program: "BPM", value: "bpm" },
  { id: 14, program: "Automation", value: "automation" },
  { id: 15, program: "Cloud Computing", value: "cloudcomputing" },
  { id: 16, program: "Testing", value: "testing" },
  { id: 17, program: "Scripting", value: "scripting" },
  { id: 18, program: "Spring Boot", value: "springboot" },
  { id: 19, program: "Security", value: "security" },
  { id: 20, program: "Mainframe", value: "mainframe" },
  { id: 21, program: "Web Dev", value: "webdev" },
  { id: 22, program: "CRM", value: "crm" },
  { id: 23, program: "Messaging", value: "messaging" },
  { id: 24, program: "Virtualization", value: "virtualization" },
  { id: 25, program: "Design Pattern", value: "designpattern" },
  { id: 26, program: "Microservices", value: "microservices" },
  { id: 27, program: "ECM", value: "ecm" },
  { id: 28, program: "CICD", value: "cicd" },
  { id: 29, program: "Middleware", value: "middleware" },
  { id: 30, program: "Web Server", value: "webserver" },
  { id: 31, program: "ERP", value: "erp" },
  { id: 32, program: "Networks", value: "networks" },
  { id: 33, program: "Others", value: "others" },
];

export const cloudtechnologies = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Amazon", value: "amazon" },
  { id: 2, program: "Microsoft Azure", value: "microsoftazure" },
  { id: 3, program: "Google", value: "google" },
  { id: 4, program: "Oracle", value: "oracle" },
  { id: 5, program: "RedHat", value: "redhat" },
  { id: 6, program: "IBM", value: "ibm" },
  { id: 7, program: "Pivotal", value: "pivotal" },
  { id: 8, program: "Others", value: "cothers" },
];

export const devOps = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Agile Tools", value: "agiletools" },
  { id: 2, program: "Build Tools", value: "buildtools" },
  { id: 3, program: "Monitoring", value: "monitoring" },
  { id: 4, program: "Artifactory", value: "artifactory" },
  { id: 5, program: "Database", value: "database" },
  { id: 6, program: "Quality Management", value: "dqualitymanagement" },
  { id: 7, program: "Continuous Deployment", value: "continuousdeployment" },
  { id: 8, program: "Microservices", value: "dmicroservices" },
];

export const cloudservices = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "CISCO Trainings", value: "ciscotraining" },
  { id: 2, program: "Juniper & Genesys", value: "juniper" },
  { id: 3, program: "Security", value: "csecurity" },
  { id: 4, program: "Microsoft Trainings", value: "microsofttrainings" },
  { id: 5, program: "Unix Administration", value: "unixadministration" },
  { id: 6, program: "Mainframe / AS 400", value: "mainframe400" },
];

export const nichetrainings = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Program 1", value: "nprogram1" },
  { id: 2, program: "Program 2", value: "nprogram2" },
  { id: 3, program: "Program 3", value: "nprogram3" },
];

export const databasemanagement = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Data Visualization", value: "data_visualization" },
  { id: 2, program: "Data Analytics", value: "data_analytics" },
  { id: 3, program: "Big Data", value: "big_data" },
  { id: 4, program: "Data Integration", value: "data_integration" },
  { id: 5, program: "No SQL", value: "no_sql" },
  { id: 6, program: "Database", value: "ddatabase" },
  { id: 7, program: "Business Intelligence", value: "business_intelligence" },
  { id: 8, program: "Others", value: "dothers" },
];

export const softskills = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Communication Skills", value: "communication_skills" },
  { id: 2, program: "Leadership Skills", value: "leadership_skills" },
  { id: 3, program: "Influencing", value: "influencing" },
];

export const emergingtechnologies = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Emerging Technologies", value: "emerging_technologies" },
];

export const qualitymanagement = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "Quality Management", value: "quality_management" },
];

export const projectmanagement = [
  { id: 34, program: "--Choose Program--", value: "" },
  { id: 1, program: "PROJECT MANAGEMENT", value: "project_management" },
];

// ------------------------------------------------------
// ------------------------------------------------------
// ------------------------------------------------------
// ----------Application Development--------------------------------------------

export const applicationserver = [
  { id: 1, name: "Apache Tomcat" },
  { id: 2, name: "IBM WebSphere Application Server" },
  { id: 3, name: "Oracle WebLogic Server" },
  { id: 4, name: "JBoss Application Server" },
  { id: 5, name: "Microsoft Internet Information Services (IIS)" },
  { id: 6, name: "Nginx" },
  { id: 7, name: "Jetty" },
  { id: 8, name: "GlassFish Server" },
  { id: 9, name: "Apache Geronimo" },
  { id: 10, name: "Resin Application Server" },
  { id: 11, name: "Oracle Application Server" },
  { id: 12, name: "SAP NetWeaver Application Server" },
  { id: 13, name: "JRun" },
  { id: 14, name: "Oracle iAS (Internet Application Server)" },
  { id: 15, name: "Sun Java System Application Server" },
  { id: 16, name: "WildFly (formerly JBoss AS)" },
  { id: 17, name: "Apache Karaf" },
  { id: 18, name: "WebMethods Integration Server" },
  { id: 19, name: "Red Hat JBoss Enterprise Application Platform (EAP)" },
  { id: 20, name: "Caucho Resin Application Server" },
];

export const esb = [
  { id: 1, name: "MuleSoft Anypoint Platform" },
  { id: 2, name: "IBM Integration Bus" },
  { id: 3, name: "Oracle Service Bus" },
  { id: 4, name: "TIBCO ActiveMatrix BusinessWorks" },
  { id: 5, name: "WSO2 Enterprise Integrator" },
  { id: 6, name: "Microsoft BizTalk Server" },
  { id: 7, name: "Red Hat Fuse" },
  { id: 8, name: "Software AG webMethods Integration Server" },
  { id: 9, name: "Apache ServiceMix" },
  { id: 10, name: "MuleSoft Enterprise Service Bus" },
  { id: 11, name: "Talend ESB" },
  { id: 12, name: "IBM DataPower Gateway" },
  { id: 13, name: "Oracle SOA Suite" },
  { id: 14, name: "SAP NetWeaver Process Integration (PI)" },
  { id: 15, name: "Jitterbit Harmony" },
  { id: 16, name: "Camel" },
  { id: 17, name: "WSO2 ESB" },
  { id: 18, name: "MuleSoft Mule ESB" },
  { id: 19, name: "Software AG webMethods Integration Server" },
  { id: 20, name: "Apache Synapse" },
];

export const os = [
  { id: 1, name: "Windows" },
  { id: 2, name: "macOS" },
  { id: 3, name: "Linux" },
  { id: 4, name: "Android" },
  { id: 5, name: "iOS" },
  { id: 6, name: "Unix" },
  { id: 7, name: "FreeBSD" },
  { id: 8, name: "Solaris" },
  { id: 9, name: "Ubuntu" },
  { id: 10, name: "CentOS" },
  { id: 11, name: "Red Hat Enterprise Linux" },
  { id: 12, name: "Fedora" },
  { id: 13, name: "Debian" },
  { id: 14, name: "openSUSE" },
  { id: 15, name: "IBM AIX" },
  { id: 16, name: "HP-UX" },
  { id: 17, name: "Chrome OS" },
  { id: 18, name: "BlackBerry OS" },
  { id: 19, name: "Windows Server" },
  { id: 20, name: "IBM z/OS" },
];

export const framework = [
  { id: 1, name: "Angular" },
  { id: 2, name: "React" },
  { id: 3, name: "Vue.js" },
  { id: 4, name: "Node.js" },
  { id: 5, name: "Express.js" },
  { id: 6, name: "ASP.NET" },
  { id: 7, name: "Django" },
  { id: 8, name: "Ruby on Rails" },
  { id: 9, name: "Spring" },
  { id: 10, name: "Hibernate" },
  { id: 11, name: "Laravel" },
  { id: 12, name: "Symfony" },
  { id: 13, name: "CakePHP" },
  { id: 14, name: "Zend Framework" },
  { id: 15, name: "CodeIgniter" },
  { id: 16, name: "Flutter" },
  { id: 17, name: "Ionic" },
  { id: 18, name: "Xamarin" },
  { id: 19, name: "Electron" },
  { id: 20, name: "TensorFlow" },
];

export const process = [
  { id: 1, name: "Waterfall" },
  { id: 2, name: "Agile" },
  { id: 3, name: "Scrum" },
  { id: 4, name: "Kanban" },
  { id: 5, name: "Lean" },
  { id: 6, name: "DevOps" },
  { id: 7, name: "XP (Extreme Programming)" },
  { id: 8, name: "RUP (Rational Unified Process)" },
  { id: 9, name: "Spiral" },
  { id: 10, name: "RAD (Rapid Application Development)" },
  { id: 11, name: "DSDM (Dynamic Systems Development Method)" },
  { id: 12, name: "FDD (Feature-Driven Development)" },
  { id: 13, name: "Crystal" },
  { id: 14, name: "SAFe (Scaled Agile Framework)" },
  { id: 15, name: "PMBOK (Project Management Body of Knowledge)" },
  { id: 16, name: "ITIL (Information Technology Infrastructure Library)" },
  { id: 17, name: "Six Sigma" },
  { id: 18, name: "CMMI (Capability Maturity Model Integration)" },
  { id: 19, name: "PRINCE2 (Projects In Controlled Environments)" },
  { id: 20, name: "Lean Six Sigma" },
];

export const artificialintelligence = [
  { id: 1, name: "Machine Learning" },
  { id: 2, name: "Deep Learning" },
  { id: 3, name: "Natural Language Processing" },
  { id: 4, name: "Computer Vision" },
  { id: 5, name: "Speech Recognition" },
  { id: 6, name: "Robotics" },
  { id: 7, name: "Expert Systems" },
  { id: 8, name: "Genetic Algorithms" },
  { id: 9, name: "Neural Networks" },
  { id: 10, name: "Reinforcement Learning" },
  { id: 11, name: "Cognitive Computing" },
  { id: 12, name: "Predictive Analytics" },
  { id: 13, name: "Autonomous Vehicles" },
  { id: 14, name: "Virtual Assistants" },
  { id: 15, name: "Recommendation Systems" },
  { id: 16, name: "Data Mining" },
  { id: 17, name: "Speech Synthesis" },
  { id: 18, name: "Emotion Recognition" },
  { id: 19, name: "Expert Systems" },
  { id: 20, name: "Knowledge Representation" },
];

export const as400 = [
  { id: 1, name: "RPG (Report Program Generator)" },
  { id: 2, name: "CL (Control Language)" },
  { id: 3, name: "DDS (Data Description Specifications)" },
  { id: 4, name: "COBOL/400" },
  { id: 5, name: "SQL/400" },
  { id: 6, name: "DB2/400" },
  { id: 7, name: "ILE (Integrated Language Environment)" },
  { id: 8, name: "RPG IV (RPGLE)" },
  { id: 9, name: "Query/400" },
  { id: 10, name: "CLLE (Control Language - Enhanced)" },
  { id: 11, name: "AS/400 System Administration" },
  { id: 12, name: "AS/400 Security" },
  { id: 13, name: "AS/400 Backup and Recovery" },
  { id: 14, name: "AS/400 Performance Tuning" },
  { id: 15, name: "AS/400 Networking" },
  { id: 16, name: "AS/400 High Availability" },
  { id: 17, name: "AS/400 Data Migration" },
  { id: 18, name: "AS/400 Web Development" },
  { id: 19, name: "AS/400 Modernization" },
  { id: 20, name: "AS/400 Application Integration" },
];

export const fullstack = [
  { id: 1, name: "HTML" },
  { id: 2, name: "CSS" },
  { id: 3, name: "JavaScript" },
  { id: 4, name: "React" },
  { id: 5, name: "Angular" },
  { id: 6, name: "Vue.js" },
  { id: 7, name: "Node.js" },
  { id: 8, name: "Express.js" },
  { id: 9, name: "MongoDB" },
  { id: 10, name: "MySQL" },
  { id: 11, name: "PostgreSQL" },
  { id: 12, name: "Java" },
  { id: 13, name: "Spring Boot" },
  { id: 14, name: "Python" },
  { id: 15, name: "Django" },
  { id: 16, name: "Ruby" },
  { id: 17, name: "Ruby on Rails" },
  { id: 18, name: "C#" },
  { id: 19, name: ".NET" },
  { id: 20, name: "ASP.NET" },
];

export const programminglanguages = [
  { id: 1, name: "Python" },
  { id: 2, name: "JavaScript" },
  { id: 3, name: "Java" },
  { id: 4, name: "C#" },
  { id: 5, name: "C++" },
  { id: 6, name: "Ruby" },
  { id: 7, name: "PHP" },
  { id: 8, name: "Go" },
  { id: 9, name: "Swift" },
  { id: 10, name: "Kotlin" },
  { id: 11, name: "TypeScript" },
  { id: 12, name: "Rust" },
  { id: 13, name: "Scala" },
  { id: 14, name: "Perl" },
  { id: 15, name: "Objective-C" },
  { id: 16, name: "Haskell" },
  { id: 17, name: "Lua" },
  { id: 18, name: "Shell Scripting" },
  { id: 19, name: "MATLAB" },
  { id: 20, name: "R" },
];

export const machinelearning = [
  { id: 1, name: "Python" },
  { id: 2, name: "R" },
  { id: 3, name: "TensorFlow" },
  { id: 4, name: "PyTorch" },
  { id: 5, name: "Scikit-learn" },
  { id: 6, name: "Keras" },
  { id: 7, name: "Apache Spark" },
  { id: 8, name: "Hadoop" },
  { id: 9, name: "Microsoft Azure ML" },
  { id: 10, name: "Google Cloud AutoML" },
  { id: 11, name: "IBM Watson" },
  { id: 12, name: "Amazon SageMaker" },
  { id: 13, name: "Caffe" },
  { id: 14, name: "Theano" },
  { id: 15, name: "MXNet" },
  { id: 16, name: "KNIME" },
  { id: 17, name: "Databricks" },
  { id: 18, name: "Microsoft Cognitive Toolkit" },
  { id: 19, name: "BigML" },
  { id: 20, name: "DataRobot" },
];

export const iacdevops = [
  { id: 1, name: "Terraform" },
  { id: 2, name: "Ansible" },
  { id: 3, name: "Chef" },
  { id: 4, name: "Puppet" },
  { id: 5, name: "Jenkins" },
  { id: 6, name: "GitLab CI/CD" },
  { id: 7, name: "CircleCI" },
  { id: 8, name: "Travis CI" },
  { id: 9, name: "AWS CloudFormation" },
  { id: 10, name: "Azure Resource Manager (ARM) Templates" },
  { id: 11, name: "Google Cloud Deployment Manager" },
  { id: 12, name: "Kubernetes" },
  { id: 13, name: "Docker" },
  { id: 14, name: "Packer" },
  { id: 15, name: "Vault" },
  { id: 16, name: "Prometheus" },
  { id: 17, name: "Grafana" },
  { id: 18, name: "ELK Stack (Elasticsearch, Logstash, Kibana)" },
  { id: 19, name: "Splunk" },
  { id: 20, name: "New Relic" },
];

export const iot = [
  { id: 1, name: "Arduino" },
  { id: 2, name: "Raspberry Pi" },
  { id: 3, name: "NodeMCU" },
  { id: 4, name: "ESP8266" },
  { id: 5, name: "MQTT" },
  { id: 6, name: "AWS IoT Core" },
  { id: 7, name: "Azure IoT Hub" },
  { id: 8, name: "Google Cloud IoT Core" },
  { id: 9, name: "IBM Watson IoT Platform" },
  { id: 10, name: "Sigfox" },
  { id: 11, name: "LoRaWAN" },
  { id: 12, name: "Zigbee" },
  { id: 13, name: "Bluetooth Low Energy (BLE)" },
  { id: 14, name: "Modbus" },
  { id: 15, name: "OPC UA" },
  { id: 16, name: "Edge Computing" },
  { id: 17, name: "Digital Twins" },
  { id: 18, name: "Industrial IoT (IIoT)" },
  { id: 19, name: "Smart Home Automation" },
  { id: 20, name: "IoT Security" },
];

export const bpm = [
  { id: 1, name: "IBM Business Process Manager" },
  { id: 2, name: "Appian" },
  { id: 3, name: "Pega BPM" },
  { id: 4, name: "Camunda" },
  { id: 5, name: "Oracle BPM Suite" },
  { id: 6, name: "Bonitasoft" },
  { id: 7, name: "K2" },
  { id: 8, name: "Nintex" },
  { id: 9, name: "Bizagi" },
  { id: 10, name: "Red Hat Process Automation" },
  { id: 11, name: "AuraQuantic" },
  { id: 12, name: "Ultimus BPM Suite" },
  { id: 13, name: "TIBCO BPM" },
  { id: 14, name: "Mendix" },
  { id: 15, name: "BPMN (Business Process Model and Notation)" },
  { id: 16, name: "DMN (Decision Model and Notation)" },
  { id: 17, name: "BPMN.io" },
  { id: 18, name: "Activiti" },
  { id: 19, name: "jBPM" },
  { id: 20, name: "Bonita BPM" },
];

export const automation = [
  { id: 1, name: "UiPath" },
  { id: 2, name: "Automation Anywhere" },
  { id: 3, name: "Blue Prism" },
  { id: 4, name: "WorkFusion" },
  { id: 5, name: "WinAutomation" },
  { id: 6, name: "Pega Robotic Process Automation" },
  { id: 7, name: "Kofax RPA" },
  { id: 8, name: "AntWorks" },
  { id: 9, name: "NICE Robotic Automation" },
  { id: 10, name: "OpenSpan" },
  { id: 11, name: "AutomationEdge" },
  { id: 12, name: "Botpress" },
  { id: 13, name: "TagUI" },
  { id: 14, name: "Microsoft Power Automate" },
  { id: 15, name: "Selenium" },
  { id: 16, name: "TestComplete" },
  { id: 17, name: "Cypress" },
  { id: 18, name: "Appium" },
  { id: 19, name: "Jenkins" },
  { id: 20, name: "Ansible" },
];

export const cloudcomputing = [
  { id: 1, name: "Amazon Web Services (AWS)" },
  { id: 2, name: "Microsoft Azure" },
  { id: 3, name: "Google Cloud Platform (GCP)" },
  { id: 4, name: "IBM Cloud" },
  { id: 5, name: "Oracle Cloud Infrastructure (OCI)" },
  { id: 6, name: "Alibaba Cloud" },
  { id: 7, name: "Salesforce" },
  { id: 8, name: "VMware Cloud" },
  { id: 9, name: "Red Hat OpenShift" },
  { id: 10, name: "Cisco Cloud" },
  { id: 11, name: "HP Helion" },
  { id: 12, name: "DigitalOcean" },
  { id: 13, name: "Rackspace" },
  { id: 14, name: "VMware vCloud" },
  { id: 15, name: "Citrix Cloud" },
  { id: 16, name: "Adobe Creative Cloud" },
  { id: 17, name: "SAP Cloud Platform" },
  { id: 18, name: "Kubernetes" },
  { id: 19, name: "Docker" },
  { id: 20, name: "HashiCorp Terraform" },
];

export const testing = [
  { id: 1, name: "Selenium" },
  { id: 2, name: "JUnit" },
  { id: 3, name: "TestNG" },
  { id: 4, name: "Cucumber" },
  { id: 5, name: "Jasmine" },
  { id: 6, name: "Appium" },
  { id: 7, name: "Postman" },
  { id: 8, name: "JMeter" },
  { id: 9, name: "LoadRunner" },
  { id: 10, name: "SoapUI" },
  { id: 11, name: "Sikuli" },
  { id: 12, name: "Robot Framework" },
  { id: 13, name: "RSpec" },
  { id: 14, name: "Mocha" },
  { id: 15, name: "Protractor" },
  { id: 16, name: "Gherkin" },
  { id: 17, name: "WebDriverIO" },
  { id: 18, name: "TestComplete" },
  { id: 19, name: "Sauce Labs" },
  { id: 20, name: "BrowserStack" },
];

export const scripting = [
  { id: 1, name: "JavaScript" },
  { id: 2, name: "Python" },
  { id: 3, name: "Ruby" },
  { id: 4, name: "Shell Scripting" },
  { id: 5, name: "PowerShell" },
  { id: 6, name: "Perl" },
  { id: 7, name: "Bash" },
  { id: 8, name: "PHP" },
  { id: 9, name: "Lua" },
  { id: 10, name: "Groovy" },
  { id: 11, name: "Tcl" },
  { id: 12, name: "VBScript" },
  { id: 13, name: "AWK" },
  { id: 14, name: "R" },
  { id: 15, name: "Go" },
  { id: 16, name: "Swift" },
  { id: 17, name: "TypeScript" },
  { id: 18, name: "MATLAB" },
  { id: 19, name: "Haskell" },
  { id: 20, name: "Erlang" },
];

export const springboot = [
  { id: 1, name: "Spring Boot" },
  { id: 2, name: "Spring Framework" },
  { id: 3, name: "Spring Data JPA" },
  { id: 4, name: "Spring Security" },
  { id: 5, name: "Spring Cloud" },
  { id: 6, name: "Spring MVC" },
  { id: 7, name: "Spring Integration" },
  { id: 8, name: "Spring Batch" },
  { id: 9, name: "Spring RESTful Web Services" },
  { id: 10, name: "Spring Test" },
  { id: 11, name: "Spring AOP" },
  { id: 12, name: "Spring Boot Actuator" },
  { id: 13, name: "Spring Boot DevTools" },
  { id: 14, name: "Spring Boot Data MongoDB" },
  { id: 15, name: "Spring Boot Data JDBC" },
  { id: 16, name: "Spring Boot Test" },
  { id: 17, name: "Spring Boot Security" },
  { id: 18, name: "Spring Boot Admin" },
  { id: 19, name: "Spring Boot GraphQL" },
  { id: 20, name: "Spring Boot Kafka" },
];

export const security = [
  { id: 1, name: "Altiris Client Management Suite" },
  { id: 2, name: "Antigen / Brightmail" },
  { id: 3, name: "CheckPoint" },
  { id: 4, name: "CEH (Certified Ethical Hacker)" },
  { id: 5, name: "Certified Information System Security Professional – CISSP" },
  { id: 6, name: "Palo Alto" },
  { id: 7, name: "WAF" },
  { id: 8, name: "CISCO ASA Firewall Solutions" },
  { id: 9, name: "F5" },
  { id: 10, name: "Intrusion Prevention System" },
  { id: 11, name: "Cyber Security" },
  { id: 12, name: "Data Protection Manager" },
  { id: 13, name: "ForeFront" },
  { id: 14, name: "Fortigate" },
  { id: 15, name: "IDS" },
  { id: 16, name: "Juniper" },
  { id: 17, name: "Symantec" },
];

export const mainframe = [
  { id: 1, name: "ADABAS" },
  { id: 2, name: "ADSA/ADSO" },
  { id: 3, name: "Assembler" },
  { id: 4, name: "CICS" },
  { id: 5, name: "CLIST" },
  { id: 6, name: "COBOL" },
  { id: 7, name: "IDMS" },
  { id: 8, name: "IMS" },
  { id: 9, name: "Mainframe Scripting" },
  { id: 10, name: "MVS" },
  { id: 11, name: "OS/2" },
  { id: 12, name: "OS390" },
  { id: 13, name: "PL/1" },
  { id: 14, name: "PRO*C" },
  { id: 15, name: "QME" },
  { id: 16, name: "QSAM" },
  { id: 17, name: "REXX" },
  { id: 18, name: "Synon" },
  { id: 19, name: "VSAM" },
  { id: 20, name: "XBRL" },
];

export const webdev = [
  { id: 1, name: "HTML" },
  { id: 2, name: "CSS" },
  { id: 3, name: "JavaScript" },
  { id: 4, name: "React" },
  { id: 5, name: "Angular" },
  { id: 6, name: "Vue.js" },
  { id: 7, name: "Node.js" },
  { id: 8, name: "Express.js" },
  { id: 9, name: "PHP" },
  { id: 10, name: "Laravel" },
  { id: 11, name: "Python" },
  { id: 12, name: "Django" },
  { id: 13, name: "Ruby" },
  { id: 14, name: "Ruby on Rails" },
  { id: 15, name: "Java" },
  { id: 16, name: "Spring Boot" },
  { id: 17, name: "ASP.NET" },
  { id: 18, name: "C#" },
  { id: 19, name: "SQL" },
  { id: 20, name: "MongoDB" },
];

export const crm = [
  { id: 1, name: "Salesforce" },
  { id: 2, name: "Microsoft Dynamics 365" },
  { id: 3, name: "HubSpot CRM" },
  { id: 4, name: "Zoho CRM" },
  { id: 5, name: "SAP Sales Cloud" },
  { id: 6, name: "Oracle CRM" },
  { id: 7, name: "SugarCRM" },
  { id: 8, name: "Pipedrive" },
  { id: 9, name: "Freshsales" },
  { id: 10, name: "Insightly" },
  { id: 11, name: "Zendesk Sell" },
  { id: 12, name: "Copper" },
  { id: 13, name: "Agile CRM" },
  { id: 14, name: "Bitrix24" },
  { id: 15, name: "Nimble" },
  { id: 16, name: "Capsule CRM" },
  { id: 17, name: "Apptivo" },
  { id: 18, name: "Keap" },
  { id: 19, name: "Close" },
  { id: 20, name: "amoCRM" },
];

// undone
export const messaging = [
  { id: 1, name: "JMS" },
  { id: 2, name: "JMX" },
  { id: 3, name: "SQS" },
  { id: 4, name: "RabbitMQ" },
];

export const containers = [
  { id: 1, name: "Docker" },
  { id: 2, name: "Kubernetes" },
  { id: 3, name: "OpenShift" },
  { id: 4, name: "Amazon ECS" },
  { id: 5, name: "Google Kubernetes Engine" },
  { id: 6, name: "Microsoft Azure Container Instances" },
  { id: 7, name: "Rancher" },
  { id: 8, name: "Mesos" },
  { id: 9, name: "Nomad" },
  { id: 10, name: "LXC/LXD" },
  { id: 11, name: "CoreOS rkt" },
  { id: 12, name: "Podman" },
  { id: 13, name: "Docker Compose" },
  { id: 14, name: "Knative" },
  { id: 15, name: "Containerd" },
  { id: 16, name: "CRI-O" },
  { id: 17, name: "Singularity" },
  { id: 18, name: "Garden" },
  { id: 19, name: "Jelastic" },
  { id: 20, name: "Lando" },
];

export const designpattern = [
  { id: 1, name: ".NET Design Pattern" },
  { id: 2, name: "Java Pattern" },
  { id: 3, name: "JEE Pattern" },
  { id: 4, name: "MVC" },
  { id: 5, name: "MVP" },
  { id: 6, name: "OOAD (Object-Oriented Analysis and Design)" },
  { id: 7, name: "SOA (Service-Oriented Architecture)" },
  { id: 8, name: "Software Engineering" },
  { id: 9, name: "UML (Unified Modeling Language)" },
  { id: 10, name: "Data Structures" },
];

// undone
export const microservices = [
  { id: 1, name: "Python" },
  { id: 2, name: "Deep Learning" },
  { id: 3, name: "Machine Learning" },
  { id: 4, name: "NLP (Natural Language Processing)" },
  { id: 5, name: "Statistics Essential" },
  { id: 6, name: "Math for Data Analysis" },
  { id: 7, name: "Neural Networks" },
  { id: 8, name: "Graphical Models" },
  { id: 9, name: "Reinforcement Learning" },
];

export const cms = [
  { id: 1, name: "WordPress" },
  { id: 2, name: "Drupal" },
  { id: 3, name: "Joomla" },
  { id: 4, name: "Magento" },
  { id: 5, name: "Shopify" },
  { id: 6, name: "Wix" },
  { id: 7, name: "Squarespace" },
  { id: 8, name: "Umbraco" },
  { id: 9, name: "TYPO3" },
  { id: 10, name: "Ghost" },
  { id: 11, name: "Contentful" },
  { id: 12, name: "HubSpot CMS" },
  { id: 13, name: "Kentico CMS" },
  { id: 14, name: "Sitecore" },
  { id: 15, name: "Pimcore" },
  { id: 16, name: "Liferay" },
  { id: 17, name: "DotCMS" },
  { id: 18, name: "Concrete5" },
  { id: 19, name: "ProcessWire" },
  { id: 20, name: "Plone" },
];

export const cicd = [
  { id: 1, name: "Kubernetes" },
  { id: 2, name: "Docker" },
  { id: 3, name: "OpenShift" },
  { id: 4, name: "Amazon ECS" },
  { id: 5, name: "Google Kubernetes Engine" },
  { id: 6, name: "Azure Kubernetes Service" },
  { id: 7, name: "Rancher" },
  { id: 8, name: "Mesos" },
  { id: 9, name: "Nomad" },
  { id: 10, name: "Swarm" },
  { id: 11, name: "Cloud Foundry" },
  { id: 12, name: "Elastic Beanstalk" },
  { id: 13, name: "Pivotal Container Service" },
  { id: 14, name: "CoreOS" },
  { id: 15, name: "CRI-O" },
  { id: 16, name: "Knative" },
  { id: 17, name: "HashiCorp Vault" },
  { id: 18, name: "Portainer" },
  { id: 19, name: "D2iQ (formerly Mesosphere)" },
  { id: 20, name: "LXC (Linux Containers)" },
];

export const middleware = [
  { id: 1, name: "Apache Kafka" },
  { id: 2, name: "RabbitMQ" },
  { id: 3, name: "Apache ActiveMQ" },
  { id: 4, name: "IBM MQ" },
  { id: 5, name: "Microsoft Message Queue (MSMQ)" },
  { id: 6, name: "Redis" },
  { id: 7, name: "Apache NiFi" },
  { id: 8, name: "Oracle Service Bus" },
  { id: 9, name: "TIBCO EMS" },
  { id: 10, name: "IBM Integration Bus (IIB)" },
  { id: 11, name: "Apache Camel" },
  { id: 12, name: "Apache Solr" },
  { id: 13, name: "Elasticsearch" },
  { id: 14, name: "Apache Cassandra" },
  { id: 15, name: "MongoDB" },
  { id: 16, name: "Oracle Coherence" },
  { id: 17, name: "Hazelcast" },
  { id: 18, name: "Apache ZooKeeper" },
  { id: 19, name: "NGINX" },
  { id: 20, name: "HAProxy" },
];

export const webserver = [
  { id: 1, name: "Apache HTTP Server" },
  { id: 2, name: "NGINX" },
  { id: 3, name: "Microsoft IIS" },
  { id: 4, name: "LiteSpeed Web Server" },
  { id: 5, name: "Apache Tomcat" },
  { id: 6, name: "Node.js" },
  { id: 7, name: "IBM HTTP Server" },
  { id: 8, name: "Jetty" },
  { id: 9, name: "Oracle WebLogic Server" },
  { id: 10, name: "Jboss Web Server (formerly Apache Tomcat)" },
  { id: 11, name: "Caddy" },
  { id: 12, name: "Cherokee" },
  { id: 13, name: "Lighttpd" },
  { id: 14, name: "OpenLiteSpeed" },
  { id: 15, name: "uWSGI" },
  { id: 16, name: "Gunicorn" },
  { id: 17, name: "Resin" },
  { id: 18, name: "Zeus Web Server" },
  { id: 19, name: "Sun Java System Web Server" },
  { id: 20, name: "Abyss Web Server" },
];

export const erp = [
  { id: 1, name: "SAP ERP" },
  { id: 2, name: "Oracle ERP Cloud" },
  { id: 3, name: "Microsoft Dynamics 365" },
  { id: 4, name: "Infor ERP" },
  { id: 5, name: "NetSuite ERP" },
  { id: 6, name: "Epicor ERP" },
  { id: 7, name: "Sage Intacct" },
  { id: 8, name: "Workday ERP" },
  { id: 9, name: "Acumatica Cloud ERP" },
  { id: 10, name: "SYSPRO ERP" },
  { id: 11, name: "IFS Applications" },
  { id: 12, name: "Odoo ERP" },
  { id: 13, name: "QAD ERP" },
  { id: 14, name: "Abas ERP" },
  { id: 15, name: "Unit4 ERP" },
  { id: 16, name: "Epicor Prophet 21" },
  { id: 17, name: "Plex ERP" },
  { id: 18, name: "Ramco ERP" },
  { id: 19, name: "Deltek ERP" },
  { id: 20, name: "Sage X3" },
];

export const networks = [
  { id: 1, name: "Ethernet" },
  { id: 2, name: "TCP/IP" },
  { id: 3, name: "Wireless LAN" },
  { id: 4, name: "Routing" },
  { id: 5, name: "Switching" },
  { id: 6, name: "Firewalls" },
  { id: 7, name: "Virtual Private Networks (VPNs)" },
  { id: 8, name: "Network Security" },
  { id: 9, name: "Network Monitoring" },
  { id: 10, name: "Load Balancing" },
  { id: 11, name: "Wide Area Networks (WAN)" },
  { id: 12, name: "Local Area Networks (LAN)" },
  { id: 13, name: "Wireless Networks" },
  { id: 14, name: "Internet of Things (IoT)" },
  { id: 15, name: "Software-Defined Networking (SDN)" },
  { id: 16, name: "Network Virtualization" },
  { id: 17, name: "VoIP (Voice over IP)" },
  { id: 18, name: "Network Protocols" },
  { id: 19, name: "Network Troubleshooting" },
  { id: 20, name: "Network Performance Optimization" },
];

export const others = [
  { id: 1, name: "Asset Manager 9.x Tailoring" },
  { id: 2, name: "Commerce Server" },
  { id: 3, name: "Cyber Ark" },
  { id: 4, name: "Excel" },
  { id: 5, name: "Lync Server" },
  { id: 6, name: "MS Access" },
  { id: 7, name: "MS Office" },
  { id: 8, name: "Oracle IDM & AM" },
  { id: 9, name: "SCADA" },
  { id: 10, name: "VBA for Excel" },
  { id: 11, name: "Visual Studio Team Foundation Server - VSTFS" },
];

// cloud technologies
export const amazon = [
  { id: 1, name: "AWS SysOps Administrator" },
  { id: 2, name: "AWS DevOps Engineer" },
  { id: 3, name: "Systems Operations on AWS" },
  { id: 4, name: "AWS Solutions Architect – Associate" },
  { id: 5, name: "Advanced Architecting on AWS" },
];

export const microsoftazure = [
  { id: 1, name: "Azure Infrastructure and Deployment" },
  { id: 2, name: "Azure Integration and Security" },
  { id: 3, name: "Azure Architect Technologies" },
  { id: 4, name: "Azure Fundamentals" },
  { id: 5, name: "O365" },
  { id: 6, name: "AZ100" },
  { id: 7, name: "AZ103" },
  { id: 8, name: "AZ300" },
  { id: 9, name: "AZ400" },
  { id: 10, name: "AZ900 / M500" },
];

export const google = [
  { id: 1, name: "Architecting with Google Cloud Platform: Infrastructure" },
  { id: 2, name: "Google Cloud Fundamentals: Core Infrastructure" },
  { id: 3, name: "Networking in Google Cloud Platform" },
  { id: 4, name: "Security in Google Cloud Platform" },
];

export const oracle = [
  { id: 1, name: "Oracle VM" },
  { id: 2, name: "Identity Cloud" },
  { id: 3, name: "Data Integration Cloud" },
  { id: 4, name: "Database Cloud" },
  { id: 5, name: "Oracle Cloud Infrastructure" },
];

export const redhat = [
  { id: 1, name: "OpenStack" },
  { id: 2, name: "RedHat Virtualization" },
  { id: 3, name: "OpenShift" },
  { id: 4, name: "Docker" },
  { id: 5, name: "Kubernetes" },
];

export const ibm = [
  { id: 1, name: "WAS" },
  { id: 2, name: "Tivoli" },
  { id: 3, name: "Netcool" },
  { id: 4, name: "Data" },
  { id: 5, name: "MQ" },
];

export const pivotal = [
  { id: 1, name: "Pivotal Cloud Foundry Operator" },
  { id: 2, name: "Pivotal GemFire Administrator" },
];

export const cothers = [
  { id: 1, name: "CCC - CTS" },
  { id: 2, name: "PSCA" },
  { id: 3, name: "PSRCA" },
  { id: 4, name: "CCSP" },
  { id: 5, name: "CISSP" },
  { id: 6, name: "CISP" },
];

// devops

export const agiletools = [
  { id: 1, name: "Jira" },
  { id: 2, name: "Trello" },
  { id: 3, name: "Azure DevOps" },
  { id: 4, name: "GitHub Projects" },
  { id: 5, name: "VersionOne" },
  { id: 6, name: "Rally" },
  { id: 7, name: "Targetprocess" },
  { id: 8, name: "Pivotal Tracker" },
  { id: 9, name: "Asana" },
  { id: 10, name: "Basecamp" },
  { id: 11, name: "Monday.com" },
  { id: 12, name: "Clubhouse" },
  { id: 13, name: "Scrumwise" },
  { id: 14, name: "Team Foundation Server (TFS)" },
  { id: 15, name: "Kanbanize" },
  { id: 16, name: "LeanKit" },
  { id: 17, name: "Wrike" },
  { id: 18, name: "Mingle" },
  { id: 19, name: "Teamwork" },
  { id: 20, name: "Yodiz" },
];

export const buildtools = [
  { id: 1, name: "Maven" },
  { id: 2, name: "Gradle" },
  { id: 3, name: "Ant" },
  { id: 4, name: "Make" },
  { id: 5, name: "MSBuild" },
  { id: 6, name: "npm" },
  { id: 7, name: "Yarn" },
  { id: 8, name: "Gulp" },
  { id: 9, name: "Grunt" },
  { id: 10, name: "Bazel" },
  { id: 11, name: "Cake" },
  { id: 12, name: "Buck" },
  { id: 13, name: "SCons" },
  { id: 14, name: "Rake" },
  { id: 15, name: "CMake" },
  { id: 16, name: "SBT" },
  { id: 17, name: "Cocoapods" },
  { id: 18, name: "Leiningen" },
  { id: 19, name: "Bower" },
  { id: 20, name: "Pants" },
];

export const monitoring = [
  { id: 1, name: "Nagios" },
  { id: 2, name: "Zabbix" },
  { id: 3, name: "Datadog" },
  { id: 4, name: "Prometheus" },
  { id: 5, name: "Grafana" },
  { id: 6, name: "New Relic" },
  { id: 7, name: "Dynatrace" },
  { id: 8, name: "Splunk" },
  { id: 9, name: "ELK Stack" },
  { id: 10, name: "Sensu" },
  { id: 11, name: "Icinga" },
  { id: 12, name: "AppDynamics" },
  { id: 13, name: "SolarWinds" },
  { id: 14, name: "Graylog" },
  { id: 15, name: "Cacti" },
  { id: 16, name: "Netdata" },
  { id: 17, name: "Opsview" },
  { id: 18, name: "Zenoss" },
  { id: 19, name: "Pingdom" },
  { id: 20, name: "Monit" },
];

export const artifactory = [
  { id: 1, name: "JFrog Artifactory" },
  { id: 2, name: "Sonatype Nexus Repository" },
  { id: 3, name: "GitLab Container Registry" },
  { id: 4, name: "Docker Registry" },
  { id: 5, name: "AWS CodeArtifact" },
  { id: 6, name: "Microsoft Azure Artifacts" },
  { id: 7, name: "Google Container Registry" },
  { id: 8, name: "Jenkins Artifactory Plugin" },
  { id: 9, name: "Apache Archiva" },
  { id: 10, name: "JCenter" },
  { id: 11, name: "PyPI" },
  { id: 12, name: "npm Registry" },
  { id: 13, name: "NuGet" },
  { id: 14, name: "Maven Central Repository" },
  { id: 15, name: "Puppet Forge" },
  { id: 16, name: "RubyGems" },
  { id: 17, name: "Gradle Plugins Portal" },
  { id: 18, name: "CocoaPods" },
  { id: 19, name: "Conda" },
  { id: 20, name: "Helm Chart Repository" },
];

export const database = [
  { id: 1, name: "Oracle Database" },
  { id: 2, name: "MySQL" },
  { id: 3, name: "Microsoft SQL Server" },
  { id: 4, name: "PostgreSQL" },
  { id: 5, name: "MongoDB" },
  { id: 6, name: "Redis" },
  { id: 7, name: "Amazon RDS" },
  { id: 8, name: "IBM Db2" },
  { id: 9, name: "SQLite" },
  { id: 10, name: "Cassandra" },
  { id: 11, name: "Apache HBase" },
  { id: 12, name: "Google Cloud Spanner" },
  { id: 13, name: "MariaDB" },
  { id: 14, name: "Amazon DynamoDB" },
  { id: 15, name: "Neo4j" },
  { id: 16, name: "Elasticsearch" },
  { id: 17, name: "Couchbase" },
  { id: 18, name: "Firebase Realtime Database" },
  { id: 19, name: "InfluxDB" },
  { id: 20, name: "Apache Derby" },
];

export const dqualitymanagement = [
  { id: 1, name: "Continuous Integration" },
  { id: 2, name: "Continuous Delivery" },
  { id: 3, name: "Automated Testing" },
  { id: 4, name: "Configuration Management" },
  { id: 5, name: "Infrastructure as Code" },
  { id: 6, name: "Continuous Monitoring" },
  { id: 7, name: "Release Management" },
  { id: 8, name: "Deployment Automation" },
  { id: 9, name: "Collaborative Development" },
  { id: 10, name: "Version Control" },
  { id: 11, name: "DevOps Metrics and Reporting" },
  { id: 12, name: "Security Integration" },
  { id: 13, name: "Agile Practices" },
  { id: 14, name: "Change Management" },
  { id: 15, name: "Risk Management" },
  { id: 16, name: "Continuous Improvement" },
  { id: 17, name: "Quality Assurance" },
  { id: 18, name: "Automated Release Validation" },
  { id: 19, name: "Service Level Monitoring" },
  { id: 20, name: "Error Tracking and Logging" },
];

export const continuousdeployment = [
  { id: 1, name: "Chef" },
  { id: 2, name: "Puppet" },
  { id: 3, name: "Ansible" },
  { id: 4, name: "SaltStack" },
  { id: 5, name: "Jenkins" },
  { id: 6, name: "Travis CI" },
  { id: 7, name: "CircleCI" },
  { id: 8, name: "GitLab CI/CD" },
  { id: 9, name: "TeamCity" },
  { id: 10, name: "Bamboo" },
  { id: 11, name: "AWS CodePipeline" },
  { id: 12, name: "Azure DevOps" },
  { id: 13, name: "Google Cloud Build" },
  { id: 14, name: "Docker" },
  { id: 15, name: "Kubernetes" },
  { id: 16, name: "Helm" },
  { id: 17, name: "Spinnaker" },
  { id: 18, name: "Terraform" },
  { id: 19, name: "JFrog Artifactory" },
  { id: 20, name: "Nexus Repository Manager" },
];

export const dmicroservices = [
  { id: 1, name: "Docker" },
  { id: 2, name: "Kubernetes" },
  { id: 3, name: "OpenShift" },
  { id: 4, name: "AWS ECS" },
  { id: 5, name: "Google Kubernetes Engine (GKE)" },
  { id: 6, name: "Azure Kubernetes Service (AKS)" },
  { id: 7, name: "Istio" },
  { id: 8, name: "Linkerd" },
  { id: 9, name: "Consul" },
  { id: 10, name: "Envoy" },
  { id: 11, name: "Apache Kafka" },
  { id: 12, name: "RabbitMQ" },
  { id: 13, name: "NGINX" },
  { id: 14, name: "Spring Boot" },
  { id: 15, name: "Node.js" },
  { id: 16, name: "Express.js" },
  { id: 17, name: "Netflix OSS" },
  { id: 18, name: "Swagger" },
  { id: 19, name: "Prometheus" },
  { id: 20, name: "Grafana" },
];

// Cloud Infrastructure Services

export const ciscotraining = [
  { id: 1, name: "Cisco Certified Network Associate (CCNA)" },
  { id: 2, name: "Cisco Certified Network Professional (CCNP)" },
  { id: 3, name: "Cisco Certified Internetwork Expert (CCIE)" },
  { id: 4, name: "Cisco Certified Entry Networking Technician (CCENT)" },
  { id: 5, name: "Cisco Certified Design Associate (CCDA)" },
  { id: 6, name: "Cisco Certified Design Professional (CCDP)" },
  { id: 7, name: "Cisco Certified Design Expert (CCDE)" },
  { id: 8, name: "Cisco Certified Architect (CCAr)" },
  {
    id: 9,
    name: "Cisco Certified Network Professional - Security (CCNP Security)",
  },
  {
    id: 10,
    name: "Cisco Certified Internetwork Expert - Security (CCIE Security)",
  },
  {
    id: 11,
    name: "Cisco Certified Network Professional - Collaboration (CCNP Collaboration)",
  },
  {
    id: 12,
    name: "Cisco Certified Internetwork Expert - Collaboration (CCIE Collaboration)",
  },
  {
    id: 13,
    name: "Cisco Certified Network Professional - Data Center (CCNP Data Center)",
  },
  {
    id: 14,
    name: "Cisco Certified Internetwork Expert - Data Center (CCIE Data Center)",
  },
  {
    id: 15,
    name: "Cisco Certified Network Professional - Wireless (CCNP Wireless)",
  },
  {
    id: 16,
    name: "Cisco Certified Internetwork Expert - Wireless (CCIE Wireless)",
  },
  {
    id: 17,
    name: "Cisco Certified Network Professional - Service Provider (CCNP Service Provider)",
  },
  {
    id: 18,
    name: "Cisco Certified Internetwork Expert - Service Provider (CCIE Service Provider)",
  },
  {
    id: 19,
    name: "Cisco Certified Network Professional - DevNet (CCNP DevNet)",
  },
  { id: 20, name: "Cisco Certified DevNet Professional (DevNet Professional)" },
];

export const juniper = [
  { id: 1, name: "Juniper Networks Certified Internet Associate (JNCIA)" },
  { id: 2, name: "Juniper Networks Certified Internet Specialist (JNCIS)" },
  { id: 3, name: "Juniper Networks Certified Internet Professional (JNCIP)" },
  { id: 4, name: "Juniper Networks Certified Internet Expert (JNCIE)" },
  { id: 5, name: "Juniper Networks Certified Design Associate (JNCDA)" },
  { id: 6, name: "Juniper Networks Certified Design Specialist (JNCDS)" },
  { id: 7, name: "Juniper Networks Certified Design Professional (JNCDP)" },
  { id: 8, name: "Juniper Networks Certified Design Expert (JNCDE)" },
  { id: 9, name: "Juniper Networks Certified Support Professional (JNCSP)" },
  { id: 10, name: "Juniper Networks Certified Support Expert (JNCSE)" },
  { id: 11, name: "Juniper Networks Certified Automation Specialist (JNCAS)" },
  { id: 12, name: "Juniper Networks Certified Cloud Specialist (JNCIS-Cloud)" },
  {
    id: 13,
    name: "Juniper Networks Certified Enterprise Routing and Switching Specialist (JNCIS-ENT)",
  },
  {
    id: 14,
    name: "Juniper Networks Certified Security Specialist (JNCIS-SEC)",
  },
  {
    id: 15,
    name: "Juniper Networks Certified Specialist Security (JNCIS-SEC)",
  },
  {
    id: 16,
    name: "Juniper Networks Certified Professional Security (JNCIP-SEC)",
  },
  {
    id: 17,
    name: "Juniper Networks Certified Specialist Enterprise Routing and Switching (JNCIS-SP)",
  },
  {
    id: 18,
    name: "Juniper Networks Certified Professional Enterprise Routing and Switching (JNCIP-SP)",
  },
  { id: 19, name: "Juniper Networks Certified Design Associate (JNCDA-DC)" },
  { id: 20, name: "Juniper Networks Certified Design Specialist (JNCDS-DC)" },
];

export const csecurity = [
  { id: 1, name: "Cisco Certified Network Associate Security (CCNA Security)" },
  {
    id: 2,
    name: "Cisco Certified Network Professional Security (CCNP Security)",
  },
  {
    id: 3,
    name: "Cisco Certified Internetwork Expert Security (CCIE Security)",
  },
  { id: 4, name: "Bluetooth Security Professional" },
  {
    id: 5,
    name: "Certified Information Systems Security Professional (CISSP)",
  },
  { id: 6, name: "Certified Ethical Hacker (CEH)" },
  { id: 7, name: "CompTIA Security+" },
  { id: 8, name: "Certified Information Security Manager (CISM)" },
  { id: 9, name: "Certified Information Systems Auditor (CISA)" },
  { id: 10, name: "Certified Cloud Security Professional (CCSP)" },
  { id: 11, name: "Certified Network Defender (CND)" },
  { id: 12, name: "Certified Secure Software Lifecycle Professional (CSSLP)" },
  { id: 13, name: "Certified Information Privacy Professional (CIPP)" },
  { id: 14, name: "Certified Wireless Security Professional (CWSP)" },
  { id: 15, name: "Offensive Security Certified Professional (OSCP)" },
  { id: 16, name: "Certified Cloud Security Specialist (CCSS)" },
  { id: 17, name: "Certified Data Privacy Solutions Engineer (CDPSE)" },
  { id: 18, name: "Certified Security Analyst (ECSA)" },
  { id: 19, name: "Certified Information Security Consultant (CISC)" },
  { id: 20, name: "Certified Penetration Testing Consultant (CPTC)" },
];

export const microsofttrainings = [
  { id: 1, name: "Exchange 2013 & 2016 Admin, Deploy & Troubleshooting" },
  { id: 2, name: "Hyper V" },
  { id: 3, name: "Image Engineering with Microsoft Deployment Tool (MDT)" },
  { id: 4, name: "Microsoft Azure" },
  { id: 5, name: "Microsoft IIS Administration" },
  { id: 6, name: "Microsoft Lync Server Administration" },
  { id: 7, name: "Microsoft Office 365 Administration" },
  { id: 8, name: "Microsoft Private Cloud Deploy, Admin & Monitoring" },
  { id: 9, name: "Microsoft SharePoint Server Administration" },
  { id: 10, name: "Microsoft Sql Server 2014 Admin" },
  { id: 11, name: "Microsoft Sql Server 2016 Admin" },
  { id: 12, name: "Microsoft Sql Server Analysis Service (SSAS)" },
  { id: 13, name: "Microsoft Sql Server Integration Service(SSIS)" },
  { id: 14, name: "Microsoft Sql Server Reporting Service(SSRS)" },
  { id: 15, name: "Microsoft Windows Clustering" },
  { id: 16, name: "Microsoft Windows PowerShell Scripting" },
  { id: 17, name: "SCCM" },
  { id: 18, name: "SCOM" },
  { id: 19, name: "SCVMM" },
  { id: 20, name: "Windows 10" },
  { id: 21, name: "Windows 2012 Server Admin" },
  { id: 22, name: "Windows 2016 Server Admin" },
  { id: 23, name: "Windows Azure" },
  { id: 24, name: "Windows Intune Integration with SCCM" },
];

export const unixadministration = [
  { id: 1, name: "Apple MAC Server & Desktop Administration" },
  { id: 2, name: "IBM - HACMP - Clustering" },
  { id: 3, name: "Oracle Solaris Administration" },
  { id: 4, name: "Oracle Solaris Cluster" },
  { id: 5, name: "Oracle Solaris Virtualization" },
  { id: 6, name: "Oracle Solaris Volume Manager" },
  { id: 7, name: "RedHat Apache and Secure Web Server Administration" },
  { id: 8, name: "RedHat Certified Security Specialist (RHCSS)" },
  { id: 9, name: "RedHat Certified Virtualization Administrator (RHCVA)" },
  { id: 10, name: "RedHat Enterprise Directory Services and Authentication" },
  { id: 11, name: "RedHat Enterprise Security Network Services" },
  { id: 12, name: "RedHat Enterprise SELinux Policy Administration" },
  { id: 13, name: "RedHat OpenStack Administration" },
  { id: 14, name: "RedHat Server Hardening" },
  { id: 15, name: "RedHat Storage Server Administration" },
  { id: 16, name: "RedHat Clustering" },
  { id: 17, name: "RHCE on RHEL 7.6" },
  { id: 18, name: "SUSE Linux Enterprise 11 Administration" },
  { id: 19, name: "SUSE Linux Enterprise 11 Fundamentals" },
  { id: 20, name: "SUSE Linux Enterprise Server 11 Administration" },
  { id: 21, name: "Ubuntu 12.04 Desktop Administration" },
  { id: 22, name: "Ubuntu 12.04 Server Administration" },
];

export const mainframe400 = [
  { id: 1, name: "ADABAS" },
  { id: 2, name: "ADSA / ADSO" },
  { id: 3, name: "AS400 Programming" },
  { id: 4, name: "AS400 - Systems Admin" },
  { id: 5, name: "Assembler" },
  { id: 6, name: "CICS" },
  { id: 7, name: "CLIST" },
  { id: 8, name: "COBOL" },
  { id: 9, name: "IDMS" },
  { id: 10, name: "IMS" },
  { id: 11, name: "Mainframe Administration" },
  { id: 12, name: "Mainframe Programming" },
  { id: 13, name: "Mainframe Scripting" },
  { id: 14, name: "MQ series" },
  { id: 15, name: "MVS" },
  { id: 16, name: "OS/2" },
  { id: 17, name: "OS390" },
  { id: 18, name: "PL/1" },
  { id: 19, name: "PRO*C" },
  { id: 20, name: "QME" },
  { id: 21, name: "QSAM" },
  { id: 22, name: "REXX" },
  { id: 23, name: "Synon" },
  { id: 24, name: "VSAM" },
];

// niche training
export const nprogram1 = [
  { id: 1, name: "Azure AD" },
  { id: 2, name: "Bluecoat Proxy" },
  { id: 3, name: "Brocade Network Advisor" },
  { id: 4, name: "CA Configuration Manager" },
  { id: 5, name: "CA Network Analyser" },
  { id: 6, name: "CA Spectrum" },
  { id: 7, name: "Checkpoint Firewall Administration (CCSA & CCSE)" },
  { id: 8, name: "CISCO ISE" },
  { id: 9, name: "CISSP" },
  { id: 10, name: "CompTIA Security+ / Cloud" },
  { id: 11, name: "CWNA & CWNP" },
  { id: 12, name: "CyberArk" },
  { id: 13, name: "Database Universe" },
  { id: 14, name: "DB2" },
  { id: 15, name: "DB2 iSeries" },
  { id: 16, name: "Dell Force 10 Network" },
  { id: 17, name: "EC - Council Ethical Hacking" },
  { id: 18, name: "EMC Data domain" },
  { id: 19, name: "EMC Ionix EMC-Networker" },
  { id: 20, name: "Enterprise Password Vault" },
  { id: 21, name: "F5 LTM, GTM & ASM, APM" },
  { id: 22, name: "Good Mobile" },
];

export const nprogram2 = [
  { id: 1, name: "Hadoop Cluster Administration" },
  { id: 2, name: "HP Client Automation" },
  { id: 3, name: "HP Vertica" },
  { id: 4, name: "Hyperion Essbase" },
  { id: 5, name: "IBM - HACMP Cluster" },
  { id: 6, name: "IBM - Power VM" },
  { id: 7, name: "IBM AIX Virtualization" },
  { id: 8, name: "IBM Sterling" },
  { id: 9, name: "IBM WebSphere ESB" },
  { id: 10, name: "IBM WebSphere Message Broker" },
  { id: 11, name: "IBM WebSphere Portlet Factory" },
  { id: 12, name: "Infoblox IPAM" },
  { id: 13, name: "Ipanama" },
  { id: 14, name: "ITIL" },
  { id: 15, name: "Jboss Enterprise Portal Application" },
  { id: 16, name: "Jboss ESB" },
  { id: 17, name: "Jboss Fuse ESB with Mediation Router" },
  { id: 18, name: "Microsoft BizTalk Server" },
  { id: 19, name: "Microsoft Dynamics CRM Case management" },
  { id: 20, name: "Open - Xchange" },
  { id: 21, name: "Oracle Enterprise Manager Ops Center" },
  { id: 22, name: "Oracle Enterprise Service Bus" },
  { id: 23, name: "Windows Intune" },
];

export const nprogram3 = [
  { id: 1, name: "Palo Alto Firewall" },
  { id: 2, name: "Pega" },
  { id: 3, name: "Perl Scripting" },
  { id: 4, name: "PMP" },
  { id: 5, name: "PowerShell" },
  { id: 6, name: "Prince" },
  { id: 7, name: "Python" },
  { id: 8, name: "RedHat Jboss Fuse with Red Hat Jboss A-MQ and Camel" },
  { id: 9, name: "Riverbed Steelhead" },
  { id: 10, name: "SAP Afaria Siteminder" },
  { id: 11, name: "SOA 11g and 12c" },
  { id: 12, name: "Solaris Virtualization C DOM LDOM Zones" },
  { id: 13, name: "Splunk Administration" },
  { id: 14, name: "Sybase Database Administration" },
  { id: 15, name: "Sybase Performance Tuning" },
  { id: 16, name: "Sybase Replication Server" },
  { id: 17, name: "Symantec BackupExe" },
  { id: 18, name: "Tibco" },
  { id: 19, name: "Trend Micro Antivirus" },
  { id: 20, name: "Veritas Cluster" },
  { id: 21, name: "Veritas Volume Manager" },
  { id: 22, name: "Vignette Application Portal" },
  { id: 23, name: "Windows Azure Service Bus" },
];

// db

export const data_visualization = [
  { id: 1, name: "Tableau Desktop Certification" },
  { id: 2, name: "Power BI Certification" },
  { id: 3, name: "QlikView Developer Certification" },
  { id: 4, name: "Data Visualization and Dashboarding with D3.js" },
  { id: 5, name: "Python for Data Visualization" },
  { id: 6, name: "R Programming for Data Visualization" },
  { id: 7, name: "Advanced Excel for Data Visualization" },
  { id: 8, name: "Data Visualization with ggplot2" },
  { id: 9, name: "Data Visualization with Matplotlib" },
  { id: 10, name: "Data Visualization with Plotly" },
  { id: 11, name: "Data Visualization with Seaborn" },
  { id: 12, name: "Data Visualization with Dimple.js" },
  { id: 13, name: "Data Visualization with Highcharts" },
  { id: 14, name: "Data Visualization with Google Data Studio" },
  { id: 15, name: "Data Visualization with Periscope Data" },
  { id: 16, name: "Data Visualization with Looker" },
  { id: 17, name: "Data Visualization with Microsoft Excel" },
  { id: 18, name: "Data Visualization with SAP Lumira" },
  { id: 19, name: "Data Visualization with Oracle Data Visualization" },
  { id: 20, name: "Data Visualization with IBM Cognos Analytics" },
];

export const data_analytics = [
  { id: 1, name: "Cassandra Fundamentals" },
  { id: 2, name: "Cloudera Data Analyst Training" },
  { id: 3, name: "Storm Real-time Data Processing" },
  { id: 4, name: "Hadoop Administration and Analytics" },
  { id: 5, name: "Data Science with Python" },
  { id: 6, name: "Data Science with R" },
  { id: 7, name: "Data Analytics with SQL" },
  { id: 8, name: "Big Data Analytics with Spark" },
  { id: 9, name: "Machine Learning for Data Analytics" },
  { id: 10, name: "Predictive Analytics and Data Mining" },
  { id: 11, name: "Text Analytics and Natural Language Processing" },
  { id: 12, name: "Data Visualization for Analytics" },
  { id: 13, name: "Data Warehousing and ETL" },
  { id: 14, name: "Data Analytics for Business Intelligence" },
  { id: 15, name: "Streaming Analytics with Kafka" },
  { id: 16, name: "Data Analytics with Tableau" },
  { id: 17, name: "Data Analytics with Power BI" },
  { id: 18, name: "Data Analytics with Python Libraries" },
  { id: 19, name: "Data Analytics with R Programming" },
  { id: 20, name: "Data Analytics with SAS" },
];

export const big_data = [
  { id: 1, name: "Cassandra Fundamentals" },
  { id: 2, name: "Hive Data Warehousing and Analytics" },
  { id: 3, name: "AWS Certified SysOps Administrator" },
  { id: 4, name: "Hadoop Administration and Analytics" },
  { id: 5, name: "Big Data Analytics with Spark" },
  { id: 6, name: "Data Science with Python for Big Data" },
  { id: 7, name: "Data Engineering with Apache Kafka" },
  { id: 8, name: "Data Engineering with Apache Flume" },
  { id: 9, name: "Data Engineering with Apache Sqoop" },
  { id: 10, name: "Data Engineering with Apache Nifi" },
  { id: 11, name: "Data Engineering with Apache Storm" },
  { id: 12, name: "Data Engineering with Apache Flink" },
  { id: 13, name: "Data Engineering with Apache Beam" },
  { id: 14, name: "Data Engineering with Apache Airflow" },
  { id: 15, name: "Data Warehousing and ETL" },
  { id: 16, name: "Data Lake Architecture and Design" },
  { id: 17, name: "Real-time Stream Processing with Kafka and Spark" },
  { id: 18, name: "Big Data Visualization with Tableau" },
  { id: 19, name: "Big Data Analytics with Python" },
  { id: 20, name: "Big Data Analytics with R Programming" },
];

export const data_integration = [
  { id: 1, name: "Oracle Data Integration and ETL" },
  { id: 2, name: "Hyperion Data Integration and Reporting" },
  { id: 3, name: "Microstrategy Data Integration and Analytics" },
  { id: 4, name: "Informatica PowerCenter ETL" },
  { id: 5, name: "Talend Data Integration and ETL" },
  { id: 6, name: "SSIS (SQL Server Integration Services)" },
  { id: 7, name: "IBM InfoSphere DataStage" },
  { id: 8, name: "Pentaho Data Integration and ETL" },
  { id: 9, name: "SAP Data Services" },
  { id: 10, name: "Azure Data Factory" },
  { id: 11, name: "AWS Glue Data Integration" },
  { id: 12, name: "Google Cloud Dataflow" },
  { id: 13, name: "Apache NiFi Data Integration" },
  { id: 14, name: "StreamSets Data Collector" },
  { id: 15, name: "HVR Data Integration" },
  { id: 16, name: "SnapLogic Integration Platform" },
  { id: 17, name: "Dell Boomi Integration Platform" },
  { id: 18, name: "MuleSoft Anypoint Platform" },
  { id: 19, name: "Jitterbit Data Integration" },
  { id: 20, name: "Actian Data Integration" },
];

export const no_sql = [
  { id: 1, name: "MongoDB" },
  { id: 2, name: "Cassandra" },
  { id: 3, name: "Redis" },
  { id: 4, name: "Amazon DynamoDB" },
  { id: 5, name: "Apache CouchDB" },
  { id: 6, name: "Neo4j" },
  { id: 7, name: "Elasticsearch" },
  { id: 8, name: "HBase" },
  { id: 9, name: "Couchbase Server" },
  { id: 10, name: "Riak" },
  { id: 11, name: "ArangoDB" },
  { id: 12, name: "Azure Cosmos DB" },
  { id: 13, name: "Google Cloud Firestore" },
  { id: 14, name: "IBM Cloudant" },
  { id: 15, name: "MarkLogic" },
  { id: 16, name: "RethinkDB" },
  { id: 17, name: "Apache Kafka" },
  { id: 18, name: "Apache Accumulo" },
  { id: 19, name: "OrientDB" },
  { id: 20, name: "Apache Flink" },
];

export const ddatabase = [
  {
    id: 1,
    name: "DB2",
  },
  {
    id: 2,
    name: "Microsoft SQL Server",
  },
  {
    id: 3,
    name: "MySQL",
  },
  {
    id: 4,
    name: "Oracle",
  },
  {
    id: 5,
    name: "MariaDB",
  },
  {
    id: 6,
    name: "PostgreSQL",
  },
  {
    id: 7,
    name: "Exadata",
  },
  {
    id: 8,
    name: "Oracle GoldenGate",
  },
  {
    id: 9,
    name: "Hybris",
  },
  {
    id: 10,
    name: "IDMS/ADSO",
  },
  {
    id: 11,
    name: "MF IMS",
  },
  {
    id: 12,
    name: "Oracle Data Guard",
  },
  {
    id: 13,
    name: "Oracle RAC Administration",
  },
  {
    id: 14,
    name: "Advanced SQL Fine Tuning",
  },
  {
    id: 15,
    name: "T-SQL",
  },
];

export const business_intelligence = [
  {
    id: 1,
    name: "Business Objects XIR2",
  },
  {
    id: 2,
    name: "Cognos Report Net",
  },
  {
    id: 3,
    name: "Crystal Reports",
  },
  {
    id: 4,
    name: "Datastage",
  },
  {
    id: 5,
    name: "Datastage Using Parallel Extender",
  },
  {
    id: 6,
    name: "Hyperion",
  },
  {
    id: 7,
    name: "In Memory BI",
  },
  {
    id: 8,
    name: "MongoDB",
  },
  {
    id: 9,
    name: "Microstrategy",
  },
  {
    id: 10,
    name: "MSBI",
  },
  {
    id: 11,
    name: "OBIEE 11g",
  },
  {
    id: 12,
    name: "Oracle OLAP",
  },
  {
    id: 13,
    name: "Pentaho",
  },
  {
    id: 14,
    name: "Performance Point Power Pivot",
  },
  {
    id: 15,
    name: "SAS",
  },
  {
    id: 16,
    name: "Teradata",
  },
];

export const dothers = [
  { id: 1, name: "MS Access" },
  { id: 2, name: "VBA for Excel" },
  { id: 3, name: "Advanced Excel" },
  { id: 4, name: "Cosmo" },
];

// softskills

export const communication_skills = [
  { id: 1, name: "Verbal Communication" },
  { id: 2, name: "Body Language" },
  { id: 3, name: "Physical Communication" },
  { id: 4, name: "Writing" },
  { id: 5, name: "Storytelling" },
  { id: 6, name: "Visual Communication" },
  { id: 7, name: "Humor" },
  { id: 8, name: "Quick-wittedness" },
  { id: 9, name: "Listening" },
  { id: 10, name: "Presentation Skills" },
  { id: 11, name: "Public Speaking" },
  { id: 12, name: "Interviewing" },
];

export const leadership_skills = [
  { id: 1, name: "Team Building" },
  { id: 2, name: "Strategic Planning" },
  { id: 3, name: "Coaching" },
  { id: 4, name: "Mentoring" },
  { id: 5, name: "Delegation" },
  { id: 6, name: "Dispute Resolution" },
  { id: 7, name: "Diplomacy" },
  { id: 8, name: "Giving Feedback" },
  { id: 9, name: "Managing Difficult Conversations" },
  { id: 10, name: "Decision Making" },
  { id: 11, name: "Performance Management" },
  { id: 12, name: "Supervising" },
  { id: 13, name: "Managing" },
  { id: 14, name: "Manager Management" },
  { id: 15, name: "Talent Management" },
  { id: 16, name: "Managing Remote Teams" },
  { id: 17, name: "Managing Virtual Teams" },
  { id: 18, name: "Crisis Management" },
];

export const influencing = [
  { id: 19, name: "Facilitation" },
  { id: 20, name: "Selling" },
  { id: 21, name: "Inspiring" },
  { id: 22, name: "Train The Trainer (TTT)" },
  { id: 23, name: "Change Management" },
  { id: 24, name: "Negotiation" },
  { id: 25, name: "Motivational Skills" },
  { id: 26, name: "Collaborating" },
  { id: 27, name: "Influential Leadership" },
  { id: 28, name: "Coaching for Improvement" },
  { id: 29, name: "Coaching for Success" },
  { id: 30, name: "Reaching Agreement" },
  { id: 31, name: "Retaining Talent" },
  { id: 32, name: "Embracing Change" },
  { id: 33, name: "Making Effective Decisions" },
  { id: 34, name: "Commercial Awareness" },
];

// emergingtechnologies
export const emerging_technologies = [
  { id: 35, name: "Artificial Intelligence" },
  { id: 36, name: "5G" },
  { id: 37, name: "Robotics" },
  { id: 35, name: "Artificial Intelligence" },
  { id: 36, name: "5G" },
  { id: 37, name: "Robotics" },
  { id: 38, name: "Blockchain" },
  { id: 39, name: "Serverless Computing" },
  { id: 40, name: "Quantum Computing" },
  { id: 35, name: "Artificial Intelligence" },
  { id: 36, name: "5G" },
  { id: 37, name: "Robotics" },
  { id: 38, name: "Blockchain" },
  { id: 39, name: "Serverless Computing" },
  { id: 40, name: "Quantum Computing" },
  { id: 41, name: "Internet of Things (IoT)" },
  { id: 42, name: "Augmented Reality/Virtual Reality (AR/VR)" },
  { id: 43, name: "Cyber Security" },
];

// QUALITY MANAGEMENT

export const quality_management = [
  { id: 44, name: "Lean Six Sigma" },
  { id: 45, name: "Quality by Deployment" },
  { id: 46, name: "Poka Yoke" },
  { id: 47, name: "Minitab" },
  { id: 48, name: "RCA using Six Sigma" },
  { id: 49, name: "Value Stream Mapping" },
  { id: 50, name: "Quality by Design" },
  { id: 51, name: "Kaizen" },
  { id: 52, name: "7QC Tools" },
];

// PROJECT MANAGEMENT
export const project_management = [
  { id: 1, name: "Prince2 Foundation" },
  { id: 2, name: "PGMP" },
  { id: 3, name: "CAPM" },
  { id: 4, name: "Prince2 Practitioner" },
  { id: 5, name: "PMP" },
  { id: 6, name: "Business Process Management" },
];
